<?php

    // Set up page title:
    $this->headTitle($this->translate('reset_password'));
?>

<div>
  <div class="box-header">
    <h2><?=$this->translate("reset_password")?></h2>
  </div>
  <?=$this->flashmessages()?>
  <br>
  <form action="<?=$this->url('content-page', ['page' => 'resetpassword'])?>" method="post">
    <p><?= $this->translate("forgot_password_info_text") ?></p>
    <div class="form-group">
      <label><?= $this->translate("Username") ?> *</label> <input type="text" class="form-control" name="cat_username" placeholder="" required="required"><br>
      <input type="button" value=<?= $this->translate("navigate_back")?> onclick="$('#modal .close').click()" class="btn btn-secondary">
      <input type="submit" value="<?= $this->translate("create_new_password")?>" class="btn btn-primary">
    </div>
  </form>

</div>
