<?php $loginMethod = $this->auth()->getManager()->getILSLoginMethod(); ?>
<?php if ('email' === $loginMethod): ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Email')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" autocomplete="username">
  </div>
<?php else: ?>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('library_number')?>:</label>
    <input type="text" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control" autocomplete="username">
  </div>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
    <input type="password" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control" autocomplete="current-password" maxlength="12">
  </div>
  <p><a href="<?=$this->url('content-page', ['page' => 'resetpassword']) ?>" data-lightbox><?=$this->transEsc('forgot_password')?></a></p>
<?php endif; ?>
